/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: dafb9a6744a4d6e067d7557328f40cb8)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "TravelAgent";
	}
	interface Env {
		AI: Ai;
		CF_ACCOUNT_ID?: string;
		CF_API_TOKEN?: string;
		TravelAgent: DurableObjectNamespace<import("./src/server").TravelAgent>;
	}
}
interface Env extends Cloudflare.Env {}
